### ISSUE TITLE
Trouble Trying to build the project

### ISSUE THREAD

**Issue by ogbautista** [AHXR/ghost#5]
Hello !
I want to use your project and possibly make an addition to it to present as a course project (improvements of existing malware are allowed), but I have had a hard time trying to build it,  and would like to ask you what compiler should I use to effectively build it.
I have tried Eclipse win Cygwin and also CodeBlocks. In the first one I have several missing headers (one of them conio.h and I don't know where to get the right header from). In Codeblocks I made a good progress but still I have one missing header "stdafx.h" I downloaded one from the internet but I am unsure if that is correct. Some of the errors are shown in the images attached. Any help is really appreciated.

Thanks!
![Img1](https://user-images.githubusercontent.com/11090294/55732006-2dabda00-59e9-11e9-9ec0-05e78fe729d4.png)

![Img2](https://user-images.githubusercontent.com/11090294/55732017-313f6100-59e9-11e9-8363-60ef695607f7.png)

**Comment by winterrdog** [comment]
Use Microsoft [Visual Studio Community](https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=Community&channel=Release&version=VS2022&source=VSLandingPage&passive=false&cid=2030#cplusplus). 

Those other IDEs will give you **headache** for this repository and most probably the author of the project was using  Microsoft Visual Studio Community.

**Comment by ogbautista** [comment]
Thanks for your reply, I'll keep it in mind for future projects.
