### ISSUE TITLE
NOT WORKING NOW !

### ISSUE THREAD

**Issue by Suvero** [AHXR/ghost#6]
Hi bro. At this moment, ghost not working or only I have problem ? I typing via cmd "C:\\...\zombie.exe 127.0.0.1 10284" and I getting after this notification from Windows like "zombie has connected" or something like that.. when I going to ghost.exe to check zombie, I click 1, or 3 to refresh, I getting this: "ERROR: There are no zombies connected.". What I doing wrong ? Or maybe it is outdated app ? Idk..

**Comment by pazmiki** [comment]
I'm sorry I don't have a solution or anything and I hope you figured everything out but I really need to ask... How did you build this?

**Comment by Piecuuu** [comment]
i have this issue too

**Comment by basketballsmash-yt** [comment]
> Hi bro. At this moment, ghost not working or only I have problem ? I typing via cmd "C:\...\zombie.exe 127.0.0.1 10284" and I getting after this notification from Windows like "zombie has connected" or something like that.. when I going to ghost.exe to check zombie, I click 1, or 3 to refresh, I getting this: "ERROR: There are no zombies connected.". What I doing wrong ? Or maybe it is outdated app ? Idk..

delete the conf file in the directory and redo the port again
make sure the port is the same for what you set when running zombie.exe
also if the port is closed then i think it wouldnt work
